### PR TITLE
added a check for real minecraft user and fixed the registration

### PR DESCRIPTION
**Pull request by munsking**

### CODE REVIEW

**Comment by PureTryOut** [comment]
Talked about this in Tox already, it's fine.

**Comment by nixi-awoo** [comment]
Not really; It does not work. Investigate it further.

**Comment by thesbros** [comment]
There's a Tox group?

**Comment by PureTryOut** [comment]
yes, give your tox id and we'll add you to it

**Comment by thesbros** [comment]
It's `916087FF4F7564AC160379B81BA70C1774F12E40AFED832CC8554742D42AB05047036AF4F5A7`

**Pull request merged**
